### ISSUE TITLE
Error on startup with latest Cauldron

### ISSUE THREAD

**Issue by ChrisLane** [lumien231/Mod-Control#3]
This error occurs on startup with the latest Cauldron: http://paste2.org/IWvGWMk1

The latest Cauldron is using the current Forge RB which is 10.13.2.1230

**Comment by lumien231** [comment]
Do you also get this error while using the "normal" forge server?

**Comment by ChrisLane** [comment]
Yes, the same happens on a vanilla forge server.
http://paste2.org/Z4p7azV8

**Comment by lumien231** [comment]
You are using Mod Control 1.0, does this also happen with the latest version?

**Comment by ChrisLane** [comment]
I was using version 1.1, maybe you didn't change the version number internally?

**Comment by lumien231** [comment]
But Modcontrol actually works fine right?
Its just that that error appears in the console.

**Comment by lumien231** [comment]
Fixed in 1.2
