### ISSUE TITLE
[Suggestion] Command to reload mod list

### ISSUE THREAD

**Issue by Eufranio** [lumien231/Mod-Control#5]
Title.

**Comment by lumien231** [comment]
There already is? /modcontrol reload

**Comment by Eufranio** [comment]
Does it work in console? Here it's giving me "unknown command" :/

**Comment by lumien231** [comment]
On which version are you?

**Comment by Eufranio** [comment]
1.7.10 - 1.2

**Comment by lumien231** [comment]
Hmm i guess i only added it in the 1.9.4 version then sorry :/.

**Comment by Zethalion** [comment]
Hi! I'd like to see it also in the 1.7.10 version since at this time, this is version used by most of the packs. It would be a great enhancement for the majority of the community.

**Comment by Eufranio** [comment]
Same, @Zethalion

**Comment by lumien231** [comment]
Sorry but i don't like to maintain mods for multiple versions of mc, especially for something small like this.

**Comment by Eufranio** [comment]
Just add this :/

**Comment by EverNife** [comment]
> /mc reload

![image](https://cloud.githubusercontent.com/assets/11357801/21300885/3607afa8-c58f-11e6-95b0-60fda4f59d4f.png)

**Comment by Eufranio** [comment]
what

**Comment by EverNife** [comment]
:v:

**Comment by Eufranio** [comment]
I dont need it anymore anyway... but which version are you using, EverNife?

**Comment by EverNife** [comment]
> ModControl-1.2.jar

**Comment by Eufranio** [comment]
rip

**Comment by EverNife** [comment]
What are you using now?
o,0

**Comment by Eufranio** [comment]
My own anti-hacked client, it checks the mods from the client, not even starting the game if something changes.

**Comment by EverNife** [comment]
Is there a server-side check too?
I was wondering to just download each mod and replace it into a cloned modpack

Anyway, i am working on a new launcher... that may solve my problems

**Comment by Eufranio** [comment]
There's no server side checks, only the normal ones (NCP). Everything is done in the client, but the server does requiere the anti-hacked client to be loaded in order to join the server, otherwise the player will be kicked.
